### PR TITLE
File structure

### PR DESCRIPTION
**Pull request by Jufebrown**
I added folders and files and installed a couple of node modules. You'll need to run npm install for them.

### CODE REVIEW

**Comment by gregkorte** [comment]
Looks like the node_modules were pushed up for some reason. When I pulled the branch down they were in the file structure, but the new dependencies were not yet installed. I thought it was a little strange after seeing the gitignore included the directory. Perhaps they were pushed before the git ignore was created?

**Comment by Jufebrown** [comment]
Yeah. I usually start the repo with a gitignore so I didn't realize it wasn't there. I thought it would take out the node modules when I pushed it up. I'll fix it when I get in.

**Comment by Jufebrown** [comment]
I deleted the node modules and pushed it up again.

**Comment by gregkorte** [comment]
Looks good. :+1:

**Pull request merged**
